### ISSUE TITLE
Make Meilix-Artwork deploy to github

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#11]
Meilix-artwork currently does not deploy the two debuild debian files to Github nor to apt.meilix.org

This ticket tracks what changes are needed to make that happen.

**Comment by abishekvashok** [comment]
Please enable Travis ci. I dont have admin rights (only write access).
https://travis-ci.org/fossasia/meilix-artwork and trigger a build, the deb files will be added to the `deb` branch on successful build.

**Comment by tabesin** [comment]
Ok. I will take care of that.

**Comment by abishekvashok** [comment]
It's enabled now. Now the question is, in which directory are the .deb files being created.

**Comment by pranav1698** [comment]
I cloned the project, and  ran the debuild.sh file; after it is finished 
Two deb files are formed in the project directory, I think this solves your query @abishekvashok

**Comment by abishekvashok** [comment]
@pranav1698 thanks
