### ISSUE TITLE
Make meilix-artwork issue tracker use the issue filing default template 

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#12]
Currently we do not use the Fossasia default template for this repo's issue tracker which aims to guide contributors of issues. This ought to be changed.

I would like to work on this task. If I don't manage to do it in a timely fashion, please go fwd yourself provided you have admin access to this repo.

**Comment by abishekvashok** [comment]
@tabesin updates?

**Comment by tabesin** [comment]
I am not sure I could do that because of permissions.

**Comment by abishekvashok** [comment]
Maybe an admin
