### ISSUE TITLE
Ensure that Meilix-Artwork complies with Debian guidelines

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#14]
Ensure that the Meilix-artwork deb package fully complies with the requirements for Debian packages.

**Comment by pranav1698** [comment]
I would like to claim this issue

**Comment by abishekvashok** [comment]
@pranav1698 you can :)

Refs:
https://wiki.debian.org/Packaging 
https://www.debian.org/doc/manuals/maint-guide/
https://wiki.debian.org/IntroDebianPackaging
https://packages.debian.org/packaging-tutorial

**Comment by pranav1698** [comment]
Thanks @abishekvashok for the references

**Comment by tabesin** [comment]
Debian proper packaging is an arcane science. It is enough to resolve it in slow steps. Check the Lintian results on Travis. You may also have a look at other artwork packages e.g. apt source xubuntu-artwork to compare what we may still be missing. Notably most artwork packages are of low quality and include artefacts from the others they were based upon.

**Comment by tabesin** [comment]
Oh, and as this is a kind of metabug claiming should not discourage others to also work on it.
