### ISSUE TITLE
Unknown substitution variable

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#15]
The debuild process hints at a problem with ${shlibs:Depends}
> pkg-gencontrol: warning: Depends field of package plymouth-meilix-logo: unknown substitution variable ${shlibs:Depends}
> dpkg-gencontrol: warning: Depends field of package plymouth-meilix-text: unknown substitution variable ${shlibs:Depends}

**Comment by pranav1698** [comment]
We can remove this variable $shlibs as other artworks like (xubuntu-artwork) do not contain this variable in the making of the package @tabesin

**Comment by pranav1698** [comment]
The built packages do not need these dependencies
