### ISSUE TITLE
64 bit issue /usr/lib/x86_64-linux-gnu/plymouth//meilix-text.so

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#19]
When installing on a 64 bit system the error may pop up:

`
W: plymouth module (/usr/lib/x86_64-linux-gnu/plymouth//meilix-text.so) missing, skipping that theme.
`

It is a known error on Ubuntu and it could be a missing dependency on plymouth label or a missing symlink. You should be able to find online how to resolve this.

**Comment by tabesin** [comment]
https://ubuntuforums.org/showthread.php?t=2322684

**Comment by tabesin** [comment]
See also https://askubuntu.com/questions/866688/label-so-is-missing

**Comment by pranav1698** [comment]
@tabesin I am claiming this issue

**Comment by pranav1698** [comment]
@tabesin, I am using 64bit-system but I am not getting the warning

**Comment by tabesin** [comment]
So the Deb file installation works? Have you activated them on your test system via update-alternatives?

**Comment by pranav1698** [comment]
I have activated them on my system successfully;
I am getting this warning with the plymouth-meilix-text package; the plymouth-meilix-logo package works fine

**Comment by tabesin** [comment]
It is a known bug on the ubuntu side lf xenial but there are fixes online.

Pranav Kulshrestha <notifications@github.com> schrieb am Sa., 27. Okt.
2018, 00:11:

**Comment by pranav1698** [comment]
I tried both the steps in both the links but the warning still remains in the text package,
Strangely when I try for xubuntu-text package there is no issue it works perfectly and the `xubuntu text` 
appears when I reboot, So I don't think this is a problem of the machine as in above but it may be because of the text-package which gets installed

**Comment by pranav1698** [comment]
The logo package works fine! What should be the next steps??
