### ISSUE TITLE
Plymouth label dependency

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#25]
I haven't checked but the text package needs a dependency on plymouth-label or sth. Please check with other -artwork packages and read the bzg reports about other -text packages and also see the meilix repo build.scripts. I think we manually knstall the unaccountefd dependency there while it shold be a dependency of the package itself, so apt automatically fetches and installs it.

**Comment by tabesin** [comment]
The package should have two dependencies:
plymouth 
plymouth-label

**Comment by pranav1698** [comment]
The package already contain plymouth-label dependency @tabesin

**Comment by pranav1698** [comment]
@tabesin  We can close this issue as plymouth-label is already added as a dependency
