### ISSUE TITLE
Add  .gitignore file

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#26]
Add an .gitignore file which includes the fragments you don't want to commit.

**Comment by tabesin** [comment]
see e,g, https://github.com/fossasia/meilix-generator/blob/master/.gitignore

**Comment by pranav1698** [comment]
Can I claim this issue? 
This needs to be completed fast @tabesin, The generated files are using unnecessary space in the repo

**Comment by abishekvashok** [comment]
Yes you can

**Comment by pranav1698** [comment]
Ok, I am claiming the issue
