### ISSUE TITLE
Create a job "design a logo" on OpenSourceDesign

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-artwork#3]
People at OpenSourceDesign help projects with design. Please add a job or issue on https://github.com/opensourcedesign and ask contributors to help with designing a logo. Follow up on the progress.

Into the job add the existing logo with the flower as a starting point. Meilix is a reference to "mei" in Chinese and "lix" for Linux/Unix. Include this info and include links to the projects.

**Comment by meets2tarun** [comment]
There are several options that we need to fill out. 
http://opensourcedesign.net/jobs/job-form/
For that purpose I made a gdoc which we will collectively fill before filling the entire job form.
https://goo.gl/ZAw8gL
