### ISSUE TITLE
Renaming plymouth meilix

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#32]
plymouth-meilix-text is equivalent to plymouth-theme-ubuntu-text in the ubuntu sphere. Therefore, following this convention it should be renamed plymouth-theme-meilix-text. Same for the logo package. However simple "mv" won't suffice. The whole theme has to be renamed without breaking.

**Comment by pranav1698** [comment]
I would like to claim this issue

**Comment by tabesin** [comment]
Of great importance is in this particular case testing. Also changes may break the meilix main repo which now takes the plymouth theme from our latest deb release. If so, please ensure that would be rectified.
