### ISSUE TITLE
Fix Lintian issue wrong bug number in closes 

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#38]
Lintian reports these two:

```
W: plymouth-meilix-logo: wrong-bug-number-in-closes l3:#nnnn
W: plymouth-meilix-text: wrong-bug-number-in-closes l3:#nnnn
```

See section 4.4. of the Debian Policy manual.
https://www.debian.org/doc/debian-policy/ch-source.html#debian-changelog-debian-changelog

**Comment by pranav1698** [comment]
Claiming this issue
