### ISSUE TITLE
Lintian - maintainer-script-should-not-use-update-alternatives-remove

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#56]
Lintian reports the warning:

W: plymouth-theme-meilix-text: maintainer-script-should-not-use-update-alternatives-remove postrm:33
W: plymouth-theme-meilix-logo: maintainer-script-should-not-use-update-alternatives-remove postrm:33

Background see:
https://lintian.debian.org/tags/maintainer-script-should-not-use-update-alternatives-remove.html

**Comment by pranav1698** [comment]
Claiming the issue

**Comment by ammarbinfaisal** [comment]
hi @tabesin,
is only line 33 meant to  be removed from both the files.
