### ISSUE TITLE
Change the instructions!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/meilix-artwork#61]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Some instructions given are wrong. 
Following file name is not in the folder.
![image](https://user-images.githubusercontent.com/33794760/48618549-bd5fd600-e9bf-11e8-94cd-e6c600029ae0.png)
This is what available.
![image](https://user-images.githubusercontent.com/33794760/48618525-a620e880-e9bf-11e8-98da-eaa90dbe733a.png)

**Expected behavior:**
The code should change.

**Am I working**
## Yes I'm working.

**Comment by pranav1698** [comment]
Yeah, work on it and change the name of the file 
Open up a pr and we will review it there itself
