### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#68]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
no review

**Expected behavior:**
Check the dependencies on https://github.com/fossasia/meilix-artwork/blob/master/meilix-artwork/debian/control - in particular the one on plymouth-theme-ubuntu-text if they are really necessary.

**Comment by pranav1698** [comment]
I will look onto it

**Comment by pranav1698** [comment]
Looks like plymouth-label and plymouth-theme-ubuntu-text package are installed when  plymouth package is installed hence not required
