### ISSUE TITLE
No uniform colour scheme

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-artwork#69]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior:**
Logo and Text do not follow the same colour scheme, one has a black, the other a blue background.

**Expected behavior:**
Both of them blue.

**Comment by pranav1698** [comment]
@tabesin, I have tested the cosmic release; This is automatically solved in that release 
![screenshot at 22-53-28](https://user-images.githubusercontent.com/34754265/49662859-006b1180-fa73-11e8-9d30-da68921e86b3.png)
Please review the cosmic release here: https://github.com/fossasia/meilix/issues/332

**Comment by pranav1698** [comment]
@tabesin this will also be solved when https://github.com/fossasia/meilix/pull/368 is merged

**Comment by abishekvashok** [comment]
Closing as #398 is merged
